/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 base-mesh-final.glb 
*/

import React, { useMemo } from 'react'
import * as THREE from 'three'
import { useGLTF } from '@react-three/drei'

const PUBLIC_URL = process.env.PUBLIC_URL || ''

export function Model({ onPointerMove, ...props }) {
  const { nodes, materials } = useGLTF(`${PUBLIC_URL}/final-base-1.1.glb`)

  // Create MeshBasicMaterial that keeps any textures from the original material
  const basicMaterial = useMemo(() => {
    const original = materials.grassGround_01
    return new THREE.MeshBasicMaterial({
      map: original?.map ?? null,
      color: original?.color ?? new THREE.Color(1, 1, 1),
      side: THREE.DoubleSide
    })
  }, [materials])

  return (
    <group {...props} dispose={null}>
      <mesh 
        geometry={nodes.Ground.geometry} 
        material={basicMaterial}
        onPointerMove={onPointerMove}
      />
    </group>
  )
}

useGLTF.preload(`${PUBLIC_URL}/final-base-1.1.glb`)
